export const ENDPOINTS = {
  auth: {
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    sendCode: "/auth/send-code",
    verifyCode: "/auth/verify-code",
  },
  admin: {
    login: "/admin/login",
    register: "/admin/register",
    forgotPassword: "/admin/forgot-password",
    sendCode: "/admin/send-code",
    verifyCode: "/admin/verify-code",
    doctors: "/admin/doctors",
    getDoctor: (id: string) => `/admin/doctors/${id}`,
    approveDoctor: (id: string) => `/admin/doctors/${id}/approve`,
    rejectDoctor: (id: string) => `/admin/doctors/${id}/reject`,
    changeDoctorStatus: (id: string) => `/admin/doctors/${id}/status`,
    invite: "/admin/invite",
    resendInvite: "/admin/invite/resend",
    users: "/admin/users",
    suspend: (id: string) => `/admin/suspend/${id}`,
    activate: (id: string) => `/admin/activate/${id}`,
    role: (id: string) => `/admin/role/${id}`,
  },
  doctor: {
    login: "/doctor/login",
    register: "/doctor/register",
    forgotPassword: "/doctor/forgot-password",
  },
  doctors: {
    me: "/doctors/me",
    meProfile: "/doctors/me/profile",
    completeProfile: "/doctors/me/complete-profile",
    updateProfilePicture: "/doctors/me/profile-picture",
    updateStatus: "/doctors/status",
    blockedDates: "/doctors/blocked-dates",
    removeBlockedDate: (id: string) => `/doctors/blocked-dates/${id}`,
    priceRequests: "/doctors/price-requests",
    slots: "/doctors/slots",
  },
  files: {
    upload: "/files/upload",
  },
  patients: {
    doctors: "/patients/doctors",
    doctorDetail: (id: string) => `/patients/doctors/${id}`,
  },
};
