export const ENDPOINTS = {
  auth: {
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    sendCode: "/auth/send-code",
    verifyCode: "/auth/verify-code",
  },
  admin: {
    login: "/admin/login",
    register: "/admin/register",
    forgotPassword: "/admin/forgot-password",
    sendCode: "/admin/send-code",
    verifyCode: "/admin/verify-code",
    doctors: "/admin/doctors",
    getDoctor: (id: string) => `/admin/doctors/${id}`,
    approveDoctor: (id: string) => `/admin/doctors/${id}/approve`,
    rejectDoctor: (id: string) => `/admin/doctors/${id}/reject`,
    changeDoctorStatus: (id: string) => `/admin/doctors/${id}/status`,
    pendingBlogs: "/admin/blogs/pending",
    approveBlog: (id: string) => `/admin/blogs/${id}/approve`,
    rejectBlog: (id: string) => `/admin/blogs/${id}/reject`,
  },
  doctor: {
    login: "/doctor/login",
    register: "/doctor/register",
    forgotPassword: "/doctor/forgot-password",
  },
  doctors: {
    me: "/doctors/me",
    meProfile: "/doctors/me/profile",
    completeProfile: "/doctors/me/complete-profile",
    updateProfilePicture: "/doctors/me/profile-picture",
    updateStatus: "/doctors/status",
    blockedDates: "/doctors/blocked-dates",
    removeBlockedDate: (id: string) => `/doctors/blocked-dates/${id}`,
    priceRequests: "/doctors/price-requests",
    slots: "/doctors/slots",
  },
  files: {
    upload: "/files/upload",
  },
  blogs: {
    list: "/blogs",
    detail: (id: string) => `/blogs/${id}`,
    share: (id: string) => `/blogs/${id}/share`,
    like: (id: string) => `/blogs/${id}/like`,
  },
  patients: {
    doctors: "/patients/doctors",
    doctorDetail: (id: string) => `/patients/doctors/${id}`,
  },
};
